swagger: '2.0'

info:
  version: "0.0.1"
  title: "jhist api"

basePath: /api/v1

paths:
  /players:
    get:
      description: Gets all players.
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Player"
    post:
      description: Create a player
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/PlayersPostBody"
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Player"
  /players/{id}:
    get:
      description: Gets a player
      parameters:
        - name: "id"
          in: "path"
          type: "integer"
          required: true
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Player"
    put:
      description: Set a player
      parameters:
        - name: "id"
          in: "path"
          type: "integer"
          required: true
        - name: "body"
          required: true
          in: body
          schema:
            $ref: "#/definitions/PlayersPutBody"
      responses:
        200:
          description: "Success"
    delete:
      description: Gets a player
      parameters:
        - name: "id"
          in: "path"
          type: "integer"
          required: true
      responses:
        200:
          description: "Success"

definitions:
  Player:
    type: "object"
    required:
      - id
      - name
      - score
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      score:
        type: "integer"
  PlayersPutBody:
    type: "object"
    properties:
      name:
        type: string
      score:
        type: integer
    additionalProperties: false
    required:
      - name
      - score
  PlayersPostBody:
    type: "object"
    properties:
      name:
        type: string
    additionalProperties: false
    required:
      - name
